#!/bin/bash

# Check if boiler is installed
if [ ! -d /usr/share/boiler ]; then
    echo Are you sure boiler is installed?
    echo
    echo Install boiler with \'sudo make install\'
    exit
fi

# Copy template, if it exists.
if [ ! -d $1 ]; then
    echo Usage: boiler [template]
else
    cp -r /usr/share/$1/* .
fi
