#!/bin/bash

# Check if boiler is installed
if [ ! -d /usr/share/boiler ]; then
    echo Are you sure boiler is installed?
    echo
    echo Install boiler with \'sudo make install\'
    exit
fi

# Copy template, if it exists.
if [ -d /usr/share/boiler/$1 ]; then
    cp -r /usr/share/boiler/$1/* .
else
    echo Usage: boiler [template]
fi
